### PR TITLE
Fixes #11 - Allow the user to specify the path where they would like …

### LINKED ISSUE #11: Allow the user to specify the path where they would like the upload to go.
e.g. make the (default) destination `/downloads/${NAME}/${VERSION}/`

ideally the destination would be settable by the user.

### PR DESCRIPTION
**Pull request by chr15m**
…the upload to go with the --destination flag.

### CODE REVIEW

**Comment by umlaeute** [comment]
merged (without fast-forward)

**Comment by umlaeute** [comment]
hmm, it seems like i didn't actually merge it (I guess I just forgot to push my local merge/fast-forward)

and now I cannot re-open the pull-request (supposedly because I abused/worked-on the same branch for PR #48)

**Comment by chr15m** [comment]
can `git cherry-pick 5e8eb8b`

**Comment by umlaeute** [comment]
yes of course; but then your patch doesn't really work as indicated [here](/pure-data/deken/issues/11#issuecomment-114116221), so I'm not entirely sure whether we actually *should* merge it in.

the problem is fixed (building on your PR) in #48.

**Pull request closed without merging**
