### PR TITLE
search backend api

### PR DESCRIPTION
**Pull request by umlaeute**
implements a simple API that allows multiple different search backends.

Closes https://github.com/pure-data/deken/issues/24

### CODE REVIEW

**Comment by chr15m** [comment]
Wow! This is cool.

I searched "aubio", package was shown, clicked on it, prompted for gksudo, but then nothing happened. Is this because my version of Ubuntu is so old? (12.04)

**Comment by chr15m** [comment]
I checked and pd-aubio is not installed. Is it because it depends on other libraries that I am prompted for it I do apt-get install? Is there a way to force dependencies?

**Comment by umlaeute** [comment]
it's most likely because another instance of `apt`/`apt-get`/`aptitude` is running and is locking the database.

i haven't found a way to properly detect this case, but have no added an error message if something goes wrong

**Comment by chr15m** [comment]
I don't seem to have any other process running, but the error message works for me so I'm happy to merge this. If other people run into issues we can file a bug against it later.

**Pull request merged**
