### PR TITLE
Docs on trust

### PR DESCRIPTION
**Pull request by umlaeute**

### CODE REVIEW

**Comment by umlaeute** [comment]
Closes https://github.com/pure-data/deken/issues/78

**Comment by chr15m** [comment]
Looks good. Should we move the "Trusting packages" section to below "Developers?"

**Comment by umlaeute** [comment]
dunno, i put it above "Developers" as i see two main sections in the document `deken-plugin` and `deken(cli)`. the GPG thingie definitely belongs to `deken-plugin`.

- deken-plugin
 - intro
 - advanced
- deken(cli)
 - intro
 - advanced

we *might* want to structure the document differently:

- intro
 - deken-plugin
 - deken-cli
- advanced
 - deken-plugin
 - deken-cli

however, i don't think we should muddle the structure:

- deken-plugin
 - intro
- deken-cli ("it's advanced because devs are advanced")
 - intro 
 - advanced
- deken-plugin
 - advanced

**Comment by chr15m** [comment]
Ok, good.

**Pull request merged**
