### PR TITLE
hy 0.14 initial compatibility

### PR DESCRIPTION
**Pull request by jpcima**
I try to make deken run under hy 0.14.
(because I have made the Archlinux community package, I want to make it run on distro libraries)

The problem in this version is the removal of `apply`.
For portability it raises this problem: I can't `defn apply` because it was replaced by a syntax which is rejected by older readers.

I have found a solution which reformulates the condition compilation with the help of macros.
A priori, it works in hy>=0.12, I have not tested older ones.

Please comment.

### CODE REVIEW

**Comment by umlaeute** [comment]
cool, i was fighting (a bit) with that problem last night.
i'll try to fix the appveyor build problem before merging.

**Comment by umlaeute** [comment]
so it seems your code breaks when using the Debian `hy`package, as this seems to be ignorant of it's own version (so the version-comparision fails).

would you mind amending your PR to check whether the actual symbols `nil?`, `slice` and `apply` do (not) exist rater tan relying on the hy-version?

**Comment by jpcima** [comment]
Sure I think I can do this

**Comment by jpcima** [comment]
I amended the PR. Did a quick try with 0.12 and 0.14.
However I don't manage to make 0.11 work on my system. It suffers of a strange a bug and can't run anything. Is this better?

**Pull request merged**
