### PR TITLE
Preferences (and more)

### LINKED ISSUE #142: optionally open up README after successfull installation.
oftentimes users are a bit lost after they downloaded a package via deken.
E.g. *zexy*-users are used to a Pd-extended style multi-binary library, but thye *might* get a multi-object single-file `zexy.dll` which doesn't work "as expected".

A README might help

### LINKED ISSUE #146: Re-installing does not fully replace previous installation
Files from a previous package download remain in the folder when the those files are not part of the current download. The content of the resulting external folder is not identical with content of the most recent downloaded package. 

I believe the resulting folder should contain only files from the most recent download.

Maybe Deken should wipe the old directory before extracting the new archive over it.

### PR DESCRIPTION
**Pull request by umlaeute**
preferences window for deken, which allows:
- setting the installation dir
   - presenting a list of all standard paths, with the possibility to *create* any missing directory
   - hopefully this resolves all the remaining issues @porres is having
- "uninstalling" a library before (re)installing it
  - simply removing the library-directory, if found in the current search-path (Closes #146, #149)
- opening a README after installation
  - by simply looking for a `README.deken.txt` in the library-directory and launching that (Closes #142)
- allow hiding of foreign architectures
  - simply don't show all those PDP-11 packages on your OS/2 system
- allow setting another architecture as default (highlight/only show all those PDP-11 packages on your OS/2 system(

### CODE REVIEW

**Comment by porres** [comment]
> setting the installation dir
> presenting a list of all standard paths, with the possibility to create any missing directory
> hopefully this resolves all the remaining issues @porres is having

Hi, my issues were already resolved with the new ~/Documents/Pd/externals folder

I don't personally have issues anymore, and I'm not relying on standard paths anymore. In fact, I'm ditching it all together. It has come to my attention also that what I believed to be "true" or "right" about standard paths is probably a mistake, as Pd's manual only mentions the "extra" folder as "The" Standard Path, so "user specific" and "global" standard paths should not exist. It is a kludge and a source of confusion. Thus, we either have to document it, or remove the kludge. I see benefits in deleting them and opened a PR about it: https://github.com/pure-data/pure-data/pull/183
 
One issue I can think of by dismissing standard paths is discussed here, where I propose a solution: https://github.com/pure-data/pure-data/issues/184

Cheers

**Comment by umlaeute** [comment]
the current implementation would allow for multiple views on "correctness".

**Comment by porres** [comment]
> the current implementation (in the PR) would allow for multiple views on "correctness".

Haha, cool. Including if the additional standard paths eventually "disappear" from the system? Thus just keeping the "extra" folder? I'm guessing yeah... but I just want to be sure.

**Comment by chr15m** [comment]
This is amazing.

Couple of minor things that might be good to change, although not blockers for merging this I don't think:

 * I checked "remove libraries before..." but did not see any message about removing them when I tried to re-install zexy:

```
Commencing downloading of:
http://puredata.info/Members/rdz/software/zexy-v2.2.6-(Linux-amd64-64)-externals.tar.gz
Into /home/chrism/pd-externals...
Successfully unzipped zexy-v2.2.6-(Linux-amd64-64)-externals.tar.gz into /home/chrism/pd-externals.

Added zexy to search paths
```
 
 * I have "newly installed libraries added to search path" checked but I was still prompted as to whether I wanted to add them. I'd expect to not be prompted if I have that checked.

 * Preferences button looks a bit cramped, could be good to put some spacing above it:

screenshot-annotated

Or even better put it in the "Edit -> Preferences" submenu.

**Comment by danomatika** [comment]
Let me know of any changes I can make to the Pd Path dialog to reflect this new setup, i.e. remove the externals install path option, etc.

**Comment by umlaeute** [comment]
@chr15m here's my rebuttal

### verbosity on *remove libraries*
actually the step is logged, however it is
    - logged to the Pd console (rather than the deken window)
    - logged with lower-than-normal verbosity (so you need to raise verbosity).
  i'd like to remove all status messages from the deken window (and move everything to the Pd console)

### re-asking to add paths
i guess this is caused by my personal horror of this "adding to the search path feature".
people should add their dependencies to the patch via `[declare]`.
so the check box is really about "should deken ask to add the search-path, or should it assume that you are going to to that manually in the patch?"
but i couldn't come up with a short meaningful sentence describing that.

the alternative would be to have a tri-state option `yes/no/ask`.

### preferences button
yes.
(and it probably should go into the Preferences menu anyhow, as @danomatika suggested)

**Comment by danomatika** [comment]
>i guess this is caused by my personal horror of this "adding to the search path feature".

I think if the declare -path PR is accepted, we won't need to add the path anyway. As long as the main externals download folder is in the user search paths, [declare -path] should (eventually) find things.

**Comment by umlaeute** [comment]
i think i fixed the issues @chr15m was having.

@danomatika not sure what you mean with the "Path" stuff: the deken preferences are definitely *not* replacing the `Path preferences`.

I think there should be a separate menu-entry for the deken-prefs (and the "Externals Install Directory" section in `Path` should probably go away).
it's most likely too much if you cram everything into a single page.

otoh, the "external install directory" could probably be accessible from both prefs (i'm not bought to the idea that a single piece of configuration must only be accessible via a single and obvious way, as often there is no "single obvious" way)

**Comment by danomatika** [comment]
>it's most likely too much if you cram everything into a single page.

Yeah.

One thing to note is that, since Pd on mac is basically Tk 8.5+, we could start thinking about using a Tk notebook widget for *all* the preferences and the existing separate dialogs could be panes.

**Comment by chr15m** [comment]
@umlaeute all sounds reasonable. :+1:

**Pull request merged**
