### PR TITLE
securing passwords (gpg and upload)

### PR DESCRIPTION
**Pull request by umlaeute**
(optionally) uses python-keyring to store the upload password in some secure place.
(optionally) uses gpg-agent to not have to enter the GPG-passphrase each time.
  https://github.com/pure-data/deken/issues/67

moved gpg-signing from "upload" into "package"

### CODE REVIEW

**Comment by chr15m** [comment]
I'm getting this:

```
$ deken package helloworld
Deken 0.1
Updating /home/chrism/.deken/workspace/externals/helloworld
Building /home/chrism/.deken/workspace/externals/helloworld
Build-Packaging into /home/chrism/.deken/workspace/pd-externals/helloworld(Linux-amd64-64)-externals
Attempting to GPG sign '/home/chrism/.deken/workspace/pd-externals/helloworld(Linux-amd64-64)-externals'
Traceback (most recent call last):
  File "/home/chrism/.deken/virtualenv/bin/hy", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy')()
  File "/home/chrism/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/home/chrism/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "/home/chrism/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/home/chrism/.deken/virtualenv/local/lib/python2.7/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "/home/chrism/.deken/deken.hy", line 805, in <module>
    
  File "/home/chrism/.deken/deken.hy", line 519, in main
    (defn main []
  File "/home/chrism/.deken/deken.hy", line 775, in _hy_anon_fn_79
    
  File "/home/chrism/.deken/deken.hy", line 545, in _hy_anon_fn_78
    (command arguments))))
  File "/home/chrism/.deken/deken.hy", line 461, in _hy_anon_fn_69
    (let [
  File "/home/chrism/.deken/deken.hy", line 470, in _hy_anon_fn_68
    (gpg-sign-file package-filename))))
  File "/home/chrism/.deken/deken.hy", line 254, in gpg_sign_file
    (defn gpg-sign-file [filename]
  File "/home/chrism/.deken/deken.hy", line 260, in _hy_anon_fn_34
    (do-gpg-sign-file filename signfile))))
  File "/home/chrism/.deken/deken.hy", line 473, in do_gpg_sign_file
    (if (os.path.isfile args.repository)
  File "/home/chrism/.deken/deken.hy", line 3569, in _hy_anon_fn_32
    
IOError: [Errno 2] No such file or directory: u'/home/chrism/.deken/workspace/pd-externals/helloworld(Linux-amd64-64)-externals'
```

Seems like it's skipping the zip/tgz step. Trying to figure it out now but maybe you will fix it faster than me.

**Comment by umlaeute** [comment]
in the light of #58: should we invest time in getting the build+package workflow to work?

**Comment by chr15m** [comment]
Packaging, yes. Building, no. The deken tool should be able to detect
binaries, package, and upload. It shouldn't be checking out code,
building code as I think that's now out of scope.

-- 
http://mccormick.cx/

**Comment by umlaeute** [comment]
yep; but I'm under the impression, that your broken example usage does exactly this: checkout code, build it and then package it. this uses a slightly different code path than packaging an existing directory.

at least this works for me:

    $ ls -1
    stdout
    $ ls -1 stdout/ 
    GNUmakefile.am
    GNUmakefile.in
    makefile
    stdout.c
    stdout-help.pd
    stdout.pd_linux
    $ deken package -v 0.46.6 stdout
    // ...
    $ ls -1
    stdout
    stdout-v0.46.6-(Linux-amd64-64)-externals.tar.gz
    stdout-v0.46.6-(Linux-amd64-64)-externals.tar.gz.asc

**Comment by chr15m** [comment]
No, it should only package it.

https://github.com/pure-data/deken/blob/master/deken.hy#L415-L420

**Comment by chr15m** [comment]
Ok, you are right. When I use `./helloworld` explicitly it works fine.

**Comment by umlaeute** [comment]
$ deken package -v 0.46.6 stdout
    Deken 0.1
    Packaging into stdout-v0.46.6-(Linux-amd64-64)-externals
    Attempting to GPG sign 'stdout-v0.46.6-(Linux-amd64-64)-externals.tar.gz'
    You need a passphrase to unlock the secret key for
    user: IOhannes m zmÃ¶lnig <zmoelnig@umlaeute.mur.at> ID: B65019C47F7A36F8
    in order to sign stdout-v0.46.6-(Linux-amd64-64)-externals.tar.gz
    Enter GPG passphrase:
    No valid GPG key found (continue without signing)
    [GNUPG:] USERID_HINT B65019C47F7A36F8 IOhannes m zmÃ¶lnig
    <zmoelnig@umlaeute.mur.at>
    [GNUPG:] NEED_PASSPHRASE B65019C47F7A36F8 B65019C47F7A36F8 1 0
    [GNUPG:] BAD_PASSPHRASE B65019C47F7A36F8
    gpg: no default secret key: bad passphrase
    gpg: signing failed: bad passphrase

    WARNING: Could not GPG sign the package.
    $

**Pull request merged**
