### PR TITLE
native unzipping on w32

### PR DESCRIPTION
**Pull request by umlaeute**
this adds support for natively unzipping deken-packages on w32 (without user-interaction).

we try to do this via a VBasic script (that is created on-the-fly).
only if this fails, we prompt the user to do it manually...

tested on w7 (but uses old technology, so should also work on other w32 variants)

### CODE REVIEW

**Comment by umlaeute** [comment]
after a short conversation on IRC with @reduzent it seems that it is possible to have `zip` available on w32 as well.
so i wonder whether we should prefer `zip` and use the VBscript as a fallback.

**Comment by umlaeute** [comment]
this has been merged into puredata, so it makes sense to also merge it here...

**Comment by danomatika** [comment]
Great work IOhannes.

**Comment by reduzent** [comment]
cool   (as often I'm late to the party...)

**Pull request merged**
