### PR TITLE
easywebdav2 for python3 compatibility (fixes pure-data/deken#180)

### PR DESCRIPTION
**Pull request by jpcima**

### CODE REVIEW

**Comment by umlaeute** [comment]
hmm, i'm practically using `python3` exclusively, and `easywebdav` works nicely.
so i'm not sure what this is trying to solve

**Comment by umlaeute** [comment]
ah i see,it's probably because the Debian packages which i use have this fixed...

**Comment by jpcima** [comment]
Yes, that's a correct assumption. This is the [Debian source](https://packages.debian.org/stretch/python3-easywebdav) and it contains the said patch.
Like the average user, I have deken in the virtualenv configuration so I run on vanilla libraries.

**Comment by umlaeute** [comment]
unfortunately this PR breaks the use of the (fixed) Debian packages.

luckily i've fixed this in eb10e7b68594ae51eb419a87a88b292a0fadb1ad (to be merged into master), so i'm closing this PR.

**Pull request closed without merging**
