### PR TITLE
report unzip success and renamed variables

### PR DESCRIPTION
**Pull request by umlaeute**
"destination" was weird, as it denotes the destination for the download, but the source for the unzip.
so i used "fullzipfile".
also "title" was not really the title but just the "filename" (of the zipfile)

### CODE REVIEW

**Comment by chr15m** [comment]
Thanks!

**Comment by danomatika** [comment]
If you are still planning on using tar.gz for OS X/Linux packages, does "fullzipfile" make sense?

**Comment by umlaeute** [comment]
it's a local variable, and it gets used in an exec-call to `unzip`.

**Comment by danomatika** [comment]
The tar.gz issue came up in an email discussion since zip files do not preserve links in cyclone.

**Comment by umlaeute** [comment]
so let's keep #9  and #10  open then.

**Pull request merged**
