### PR TITLE
Sourceful uploads

### PR DESCRIPTION
**Pull request by umlaeute**
naive implementation of sourcefull uploads as discussed in #88

### CODE REVIEW

**Comment by chr15m** [comment]
I have not forgotten about this. Will try to test it soon. Have looked at the code and it looks good so if you are confident about the functionality go ahead and merge. :)

**Comment by umlaeute** [comment]
:cool: take your time to merge.

i had yet another idea how to make this even more useful: track all uploaded files (i would go for *all* uploaded files, not just `Source`-archives) somewhere in a database-like file in `~/.deken/`, so it is possible to upload the non-source archives without having to pass ` --no-source-warning` (at least if you uploaded a source archive *before*)

    $ deken upload foobar-v2.3-(Source)-externals.tgz
    $ deken upload foobar-v2.3-(DOS-Sparc-128)-externals.tgz

(currently this is not possible as `deken upload` only checks the *currently* uploaded packages)

the main drawback is, that it doesn't help when uploading from multiple hosts (e.g. directly uploading from each OS/arch), so the convenience added might not be worth it...

what do you think?

**Comment by Ant1r** [comment]
Why not checking for the source package (for this external/version) inside
of the online author's repository (on puredata.info) ?

2015-12-31 20:52 GMT+01:00 umläute <notifications@github.com>:

**Comment by umlaeute** [comment]
because there is no such thing as the `online publisher's repository`

**Comment by umlaeute** [comment]
that doesn't mean though that it is a bad idea to search `puredata.info` for a *Source* package uploaded by the very user that is currently uploading. (i think it's great)

the problem is still that `deken` is so de-centralized, that you can use it to upload to some other website as well (that is not integrated into the `deken-plugin` search like puredata.info)

**Comment by umlaeute** [comment]
implemented the search on puredata.info.

**Comment by umlaeute** [comment]
@chr15m want to merge?

**Pull request merged**
